version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" 
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  hotelservice-api:
    build:
      context: .
      dockerfile: HotelService.Api/Dockerfile
    ports:
      - "5076:8080"
    networks:
      - app_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__HotelDatabase=Host=hoteldb;Port=5432;Database=hoteldb;Username=hotel_user;Password=hotel_password
    depends_on:
      - hoteldb
  report-api:
    build:
      context: .
      dockerfile: ReportService.Api/Dockerfile
    ports:
      - "5078:8080"
    networks:
      - app_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ReportDatabase=Host=reportdb;Port=5433;Database=reportdb;Username=report_user;Password=report_password
    depends_on:
      - reportdb
  hoteldb:
    image: postgres:latest
    container_name: hoteldb
    environment:
      - POSTGRES_USER=hotel_user
      - POSTGRES_PASSWORD=hotel_password
      - POSTGRES_DB=hoteldb
    ports:
      - "5432:5432"
    networks:
      - app_network

  reportdb:
    image: postgres:latest
    container_name: reportdb
    environment:
      - POSTGRES_USER=report_user
      - POSTGRES_PASSWORD=report_password
      - POSTGRES_DB=reportdb
    ports:
      - "5433:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
